package metro.entity;

public class Card {
    private int cardNo;
    private double balance;
    private int userId;

    public Card(int cardNo, double balance, int userId) {
        this.cardNo = cardNo;
        this.balance = balance;
        this.userId = userId;
    }

    // For creating new cards without cardNo (auto-generated by DB)
    public Card(double balance, int userId) {
        this.balance = balance;
        this.userId = userId;
    }

    public int getCardNo() {
        return cardNo;
    }

    public void setCardNo(int cardNo) {
        this.cardNo = cardNo;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Card{" +
                "cardNo=" + cardNo +
                ", balance=" + balance +
                ", userId=" + userId +
                '}';
    }
}
